server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: json-library-service
            uri: lb://json-library-service
            predicates:
              - Path=/api/json/**
          - id: xml-library-service
            uri: lb://xml-library-service
            predicates:
              - Path=/api/xml/**
          - id: yaml-library-service
            uri: lb://yaml-library-service
            predicates:
              - Path=/api/yaml/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0