spring:
  application:
    name: yaml-library-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: nurik05
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#logging:
#  level:
#    web: debug